### ISSUE TITLE
What is the 'pca_base_pool5.bin'?

### ISSUE THREAD

**Issue by praywj** [hmmlillian/Gray-Image-Retrieval#1]
I am sorry to bother you, but there is a problem that has been bothering me for a long time, I still want to ask you.
In **pca_func.m** of your code, like `file_name = sprintf('%s/%s/pca_base_pool5.bin', ftr_dir, cls_name);` , I want to ask you What is the 'pca_base_pool5.bin'? The Imagenet dataset I downloaded before are pictures, so I don't know what this file is.
Maybe the problem is stupid, but I still look forward to your answer.
Thank you.

**Comment by hmmlillian** [comment]
@praywj It is our precomputed and compressed features of all the ImageNet pictures. Please go to demo/ImageNet/ folder and download it: https://drive.google.com/open?id=1FS04QjIowFN2iFWqP_5lfcG6GyGH5yJE , with which you can do a fast search by directly comparing with the compressed ImageNet features.

**Comment by praywj** [comment]
Ok, thanks. It is my fault that I think it is pictures and the file is so big, so I want to confirm it. Thank you again for your answer.
