### ISSUE TITLE
compiled files

### ISSUE THREAD

**Issue by cccusername** [hmmlillian/Gray-Image-Retrieval#2]
Hello, I`m interested in your work. The link of complied file had disabled. Could you share it again? Thank you! @hmmlillian

**Comment by hmmlillian** [comment]
@cccusername Sorry for the invalid link and I have updated it in README. Please check it out. Thanks!

**Comment by cccusername** [comment]
@hmmlillian Thank you!!!

**Comment by SystemErrorWang** [comment]
@hmmlillian it seems the pre-trained vgg19_bn_gray model url is also unavailable now. Would you please check it out?

**Comment by hmmlillian** [comment]
@SystemErrorWang Updated. Please check it out. Thanks!
