### ISSUE TITLE
How much GPU memory does this network need at least?

### ISSUE THREAD

**Issue by sciart17** [hmmlillian/Gray-Image-Retrieval#7]
Hello, I tried to run the test script on my laptop(with NIVIDIA GeForce 940MX: 2GB), the program broke off at
`blobs_out = net.forward(**forward_kwargs)` 
and got the error:
```
 F0516 16:30:33.410004 13576 syncedmem.cpp:78] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
```
I would like to know how much GPU memory does this network need at least? And if there is any interface for changing parameters and running mode like https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1230#issuecomment-494417537 or any other solution to optimize the memory usage?

Thanks!

**Comment by hmmlillian** [comment]
@sciart17 I just tested this code on a notebook with a GPU of NVIDIA GeForce GTX 1070 (total memory: 8192MiB), the network of VGG19 we use to extract features takes about 1352MiB. So I think your GPU memory (2GB) may be not enough for this program. You can monitor the GPU usage using NVIDIA-SMI.

**Comment by sciart17** [comment]
I have successfully run this program on a computer with a GPU of NVIDIA GeForce GTX 1080Ti. Thank you again for your great work and reply!
